### ISSUE TITLE
Background & Lock Screen are not showing a proper preview 

### ISSUE THREAD

**Issue by MaitieS** [Xanashi/Icaros#102]
Background & Lock Screen are not showing a proper preview if Icaros's thumbnailing is enabled.

Here is a video of the issue: https://streamable.com/hcdsqb

**Comment by Xanashi** [comment]
Ah, I missed the video. However you should be able to fix it by removing png (or maybe jpg?)
from the filetypes list in Icaros. 
Windows has some weird use cases for its own shell extensions.

**Comment by MaitieS** [comment]
Oh. I didn't know that. Basically issue was that whenever I clicked on a new background that it just didn't show a preview in that window that you usually see, but when I turned off thumbnailing in Icaros it worked perfectly fine. To be fair, It's a very minor issue and easily solved by just turning it off and on after adding new or you can simpy just ignore it :D I just wanted to report it in case that no one ever mentioned it.

thx for reply!

**Comment by Xanashi** [comment]
I appreciate the report. I've known about this issue since Windows 7. 
I'm not sure why it works with the native shell extension, but not any third-party shell extensions that takes over thumbnailing of png/jpg, but I assume MS has some custom code that only works with their own extension.
Unfortunately it's not something I believe I can fix from my end.
