### ISSUE TITLE
Video border incorrectly shown on HEIC files

### ISSUE THREAD

**Issue by Jevil7452** [Xanashi/Icaros#116]
![image](https://github.com/user-attachments/assets/002021b3-4dda-4595-ab70-237d33b4bde3)
Disabling the option for video borders in Icaros disables it globally, which isn't something I want.
The same issue doesn't occur with other file formats, even if I set Icaros to generate thumbnails for it.
![image](https://github.com/user-attachments/assets/e997c8c7-6326-4b60-8def-d4a43d1bf562)
The video border is correctly shown on actual video files.
![image](https://github.com/user-attachments/assets/fdbdc6f9-fe0e-48a6-ac81-e3bb9fe2f2da)
It doesn't seem to be an issue with my icon cache, I ran `ie4uinit -show` to refresh it and the problem persisted

**Comment by Xanashi** [comment]
The option in Icaros to disable movie reels on video files is a global option, so that isn't what you're looking for.
But you're completely right, there is a bug here, Icaros should register HEIC as an image filetype, I'll make sure to fix that for the next release.
Until then you can use the attached .reg file. Make sure to refresh File Explorer afterwards (this can be done on the Tools Page of IcarosConfig).

[heic_fix.reg.txt](https://github.com/user-attachments/files/16564835/heic_fix.reg.txt)

Note: Remove the .txt extension before use

**Comment by Jevil7452** [comment]
That fixed it, thanks!

**Comment by EDSln** [comment]
> The option in Icaros to disable movie reels on video files is a global option, so that isn't what you're looking for. But you're completely right, there is a bug here, Icaros should register HEIC as an image filetype, I'll make sure to fix that for the next release. Until then you can use the attached .reg file. Make sure to refresh File Explorer afterwards (this can be done on the Tools Page of IcarosConfig).
> 
> [heic_fix.reg.txt](https://github.com/user-attachments/files/16564835/heic_fix.reg.txt)
> 
> Note: Remove the .txt extension before use

This also applies to avif images, they are also displayed as a video file. Also fixes the registry fix (I changed heic to avif in it).

**Comment by Xanashi** [comment]
Thank for reporting this EDSIn. It'll be fixed in the upcoming release of Icaros.
