### ISSUE TITLE
[Feature Request] Custom properties filetypes

### ISSUE THREAD

**Issue by Mr-Z-2697** [Xanashi/Icaros#26]
Custom properties filetypes, like thumbnail filetypes. Since we use ffmpeg, and custom thumbnail filetypes can work, this should be possible.
I saw two comments on videohelp, one for requesting mp4 type, then after mp4 is added, another one asks for ts type, so make it customizalbe would be a good solution I guess.

**Comment by Xanashi** [comment]
Unlike thumbnailing, properties are not generated with FFmpeg in Icaros, as it is not fast enough if a large number of files are selected. 
All property filetypes in Icaros, have custom file parsers written for Icaros. So that's basically why the property filetypes in Icaros are limited and why support for new filetypes are added more slowly.
