### ISSUE TITLE
Where in the registry can I find the settings from ACTIVATED / DEACTIVATED from "PROPERTIES" and "THUMBNAILING" ?

### ISSUE THREAD

**Issue by RemixPL1994** [Xanashi/Icaros#41]
Where in the registry can I find the settings from ACTIVATED / DEACTIVATED from "PROPERTIES" and "THUMBNAILING" ?

![obraz](https://user-images.githubusercontent.com/52541621/222206749-5b20c7c6-d824-457a-bbf6-f6e15ef3467f.png)
![obraz](https://user-images.githubusercontent.com/52541621/222206817-99dbeb3a-a832-4071-a595-c39e99b1750b.png)

I want to create my backup file of my own Icaros settings to .reg

I found all the settings I needed, what file types to use, what type of cache, language, etc.

But I can't find the settings in the system registry for the ACTIVATED / DEACTIVATED switch and I have to manually use it and click in the program otherwise the changes will never be fully accepted.

@Xanashi  Can I ask for help in this matter?

So far I've looked here:

HKEY_CURRENT_USER\SOFTWARE\Icaros

and

HKEY_LOCAL_MACHINE\SOFTWARE\Icaros

I also looked in the README file from Icaros after installation.

I changed the setting in the program to ACTIVATED / DEACTIVATED and looked to see if any setting in the registry had changed but I did not find any differences.

It seems that these values either do not exist at all and cannot be controlled from the registry, or they are in a different place, or I just don't know how to do it right.

Btw. If it turns out that there are currently no settings in the registry for ACTIVATED / DEACTIVATED to be able to enable or disable the "PROPERTIES" and "THUMBNAILING" settings.

Can you add this in an update?

Thanks in advance for your answer and best regards.

**Comment by Destroy666x** [comment]
@Xanashi is there any reason why properties and extensions are saved in `HKEY_LOCAL_MACHINE` rather than `HKEY_CURRENT_USER` like the rest of settings BTW? Why isn't that per user?

And another a bit less related question - I see there are some properties in registry that aren't in the interface, like `psd` or `tga`. Are they not in the interface on purpose or is this a mistake?

**Comment by Xanashi** [comment]
@RemixPL1994
I believe you got an answer to your question by Shark007, so I didn't prioritize replying to this issue, but I'll leave a reply now,
just in case other users are looking for the answer. 

The ACTIVATED / DEACTIVATED states of Icaros are not determined by a registry setting, but by whether or not the shell extensions are registered or unregistered with regsvr32.exe.
You can figure this out via the registry though, if you look for the COM registration keys (let me know if you need to more info about this),
however I still only recommend using regsvr32 to activate and deactivate Icaros.

Also IcarosConfig itself has a full export and import of the Icaros settings, if you look in the top right corner of the GUI, click the gear icon (ui settings), and then click on the button with the gear icon on this page (right of the 'Done' button). It can only be accessed when Icaros is disabled.

Hope this helps.

@Destroy666x 
Yes, there is a reason for this. When shell extensions are registered with regsvr32, all extensions are registered to the global HKLM part of the registry, that affects all users. So I keep the settings in the same part of the registry. 
It's basically the way Microsoft intended Shell Extensions to work. System-wide instead of on a per-user basis.

I have PSD and TGA in IcarosConfig:

![psd-tga](https://github.com/Xanashi/Icaros/assets/30978586/7bbe6130-be6f-4e53-bb5e-32add509e465)

You may have to download and reinstall 3.3.1 Beta 1, as I had to reupload it, right after I published the release,
due to an issue with the first binaries I uploaded.

**Comment by RemixPL1994** [comment]
For total simplicity, this can be done via CMD as administrator and:

cd\Program Files\Icaros

IcarosConfig.exe -activate
IcarosConfig.exe -deactivate

**Comment by Xanashi** [comment]
You're absolutely right. Thank you for adding this option to this thread.
It's also possible to import and export the Icaros settings using the IcarosConfig commandline, using the -settings option:

```
 -settings : Use this command to Export/Import/Reset/Delete Icaros settings
             To select the specific mode follow -settings with an
             equals and the mode:

             Export: -settings=exp or -settings=export
             Import: -settings=imp or -settings=import
             Reset:  -settings=rst or -settings=reset
             Delete: -settings=del or -settings=delete 

 -path     : Use to Export or Import the Icaros settings to/from a specific location, e.g:
             Export: -path="C:\Some\Path\Name" or
             Import: -path="C:\Some\Path\Name\IcarosSettings.icss"
```

All available commandline options can be viewed with IcarosConfig -help

**Comment by AADJND5** [comment]
I can't import the program settings from the IcarosSettings.css file using .cmd. 

cd \Program Files\Icaros

IcarosConfig.exe -path="C:\Program Files\Icaros\Ikaros Settings.icss"
IcarosConfig.exe -activate 

they are not imported. 
It is possible to import through the registry, but they are constantly enabled, that is, the file properties item is always activated. 

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Icaros]
"Thumbnail Extensions"="mov"
"Prop Local"="ru"

[HKEY_CURRENT_USER\SOFTWARE\Icaros] 
"Cache"=dword:00000002
"FrameThresh"=dword:00000008
"UseCoverArt"=dword:00000001


[HKEY_CURRENT_USER\SOFTWARE\Icaros\Cache]
"Location"="C:\\Program Files\\Icaros\\Cache"
"MaxCacheSize"=dword:000001f4

[HKEY_CURRENT_USER\SOFTWARE\Icaros\Cache\Excluded]

[HKEY_CURRENT_USER\SOFTWARE\Icaros\Cache\Locations]
"C:\\Program Files\\Icaros\\Index"=dword:02000015

[HKEY_CURRENT_USER\SOFTWARE\Icaros\Config]
"Local"="ru"
"CbxOpts"=dword:00000040

What should I add to the registry settings so that the default file properties are deactivated ? 

I ask for your help.

**Comment by Xanashi** [comment]
Hi AADJND5,

You need to add the --settings=imp parameter to your commandline e.g.:

IcarosConfig.exe -settings=imp -path="C:\Program Files\Icaros\Ikaros Settings.icss"

Icaros may have to be activated again afterwards

**Comment by AADJND5** [comment]
Dear Xanashi, I'm sorry to bother you, but I still have a few questions. Question No. 1. Where should the cache and indexing folders be located, since if I place them in the program folder in the Program files location, a message appears that the program does not have write and read permissions in this place? Question No. 2. How can I use the registry to make the thumbnail properties parameter deactivated, by default it is always activated after installing the program? Question No. 3. Does the program have silent hidden installation keys? Question number 4 When using the script.the cmd that you suggested to me pops up an error in the message: 
![001  14_12_2023](https://github.com/Xanashi/Icaros/assets/113119669/12636579-c4bf-4e69-aef6-ecdbdffe8eb0)
![1  14_12_2023](https://github.com/Xanashi/Icaros/assets/113119669/3c57428c-ef7a-42b7-9fa8-e181d5c21bdd)
![1  14_12_2023п](https://github.com/Xanashi/Icaros/assets/113119669/2f72091b-9e39-4053-8a6f-8c781b7741ad)

C:\Windows\system32 >cd \Program FilesMcaros
C:\Program FilesMcaros>IcarosConfig.exe -settings=imp -path="C:\Program Files\Icaros\IkarosSettings
IcarosThumbnailProvider.dll Deactivated Successfully! IcarosPropertyHandler.dll Deactivated Successfully! Importing settings from: c:\program files\icaros\ikarossettings.icss irt cani set the -path command to a valid settings file (.icss). IcarosThumbnailProvider.dll Activated Successfully! IcarosPropertyHandler.dll Activated Successfully!
\Program Files\Icaros>IcarosConfig.exe -activate. 

And the last Question is whether the file itself is needed for operation IcarosConfig.exe or is it enough to register a .dll and make settings in the registry? I use an online translator to communicate with you.

**Comment by Xanashi** [comment]
Hi AADJND5,

Sorry for the late reply.
No problem ask away. 

**1.** The Icaros Cache location should be placed in a folder that the current logged-in user can access wihtout administrative rights. 
If you choose a folder where this is not true, IcarosConfig will let you know (as you saw) and will then request permission to change that folders permisssions
so the folder can be accessed by the current user account.

It's also best if it's placed on a fast drive to allow faster retrieval of cached thumbnails. 

**2.** You can't use the registry to enable/disable the shell extensions. You will either have to use IcarosConfig's commandline interface or 
use regsvr32 directly on the shell extension dlls, e.g.:

Run the following in CMD:

**IcarosConfig.exe -deactivate=properties**

OR

**regsvr32 -u path/to/IcarosPropertyHandler.dll**

The above regsvr32 command will only affect the 64-bit extension. 
To also disable the 32-bit extension the WOW64 regsvr32 must be called with the same command.
Using the IcarosConfig.exe command will do both at once.

**3.** Please elaborate. By default, when Icaros is deactivated, only two keys are added to the windows registry:

**HKEY_CURRENT_USER\SOFTWARE\Icaros
HKEY_LOCAL_MACHINE\SOFTWARE\Icaros**

Was that what you were thinking about?

**4.** Could you send me the invalid settings file (.icss)?

**5.** IcarosConfig.exe is just the GUI to manage the shell extensions, the Icaros Cache and provide additional helpful tools.
It is not needed to use the shell extensions. Each shell extension can run stand alone. 
The IcarosThumbnailProvider.dll does depend on the ffmpeg .dll files and the IcarosCache.dll file though.

Hope that answers your questions. 😊
