### ISSUE TITLE
[Bug] "Display icon overlays on thumbnails" enabled, but icons in thumbnails are missing

### ISSUE THREAD

**Issue by mhetralla** [Xanashi/Icaros#49]
**Icaros version:** 3.3.1 Beta 1
**Windows version:** Windows 10 21H2

Despite "Display icon overlays on thumbnails" being enabled on IcarosConfig, no icon is showed on the bottom left of the thumbnail. I already tried to disable and enable the option, deleting the Windows thumbnail cache, refreshing and restarting Explorer and restarting the computer.

![image](https://github.com/Xanashi/Icaros/assets/15217237/2db0ccb4-b17c-4b0b-b787-01611b6701fb)

**Comment by Xanashi** [comment]
That is strange. It works on my Windows 10 machine. 

You could try toggling the option a few times and see if that helps.
Alternatively, If you open an Explorer window and select the View tab in the 'Ribbon', and the click Options,
a folder option window will appear. 

Click the View tab again in this window, and toggle the "Display file icon on thumbnails" option, and then click Apply.
This performs the same action as IcarosConfig, but it may work better using it directly from File Explorer. 
Once again, the visual changes can be a bit buggy, so you may have to toggle/apply a few times before you can visually
see the change in Explorer.

**Comment by MaitieS** [comment]
I'm experiencing similar issue but with .cbz format. Is there a way how to perform a clean unninstallation where it removes all ownerships of these thumbnail filetypes? I tried to unninstal it manually and as well clean up registers but I still had an issue with .cbz format after a reboot. Even when I try to re-enable it with cbz in it icon is just not showing up. Not that I complain but I would like to have an option to revert it back and so on.

**Comment by Xanashi** [comment]
I need to mention that Icaros itself does not touch 'icon overlays' (the small icons in the lower right of thumbnails), except for the "Display icon overlays on thumbnails" option, which is basically just a shortcut to the Windows Folder option found in the View tab. 

So disabling or uninstalling Icaros won't have any impact on these icons. 
If you're experiencing issues where filetypes are not showing the icon overlays, it is most likely caused by another software.

I've attached a potential fix, that may work for some users. Make sure that you refresh Explorer after applying the registry file.
NOTE: Remove .txt from the end of the file. Github does not allow reg files.

[FixTypeOverlayMissing.reg.txt](https://github.com/Xanashi/Icaros/files/11790872/FixTypeOverlayMissing.reg.txt)

In regards to disassociating Icaros from filetypes, simply disabling Thumbnailing and Properties in IcarosConfig, will completely
revert all filetype settings back to what they were before Icaros was enabled.

**Comment by MaitieS** [comment]
Hi Xanashi,

Thanks a lot for your .reg file. It fixed the issue.

**Comment by Xanashi** [comment]
Very glad to hear it worked. 👍

**Comment by MaitieS** [comment]
I know that this might be a bit too much to ask but I never personally found a similar thread like this even if I tried to google it in the past it usually just gave me outputs like: How to turn off/on thumbnails so sorry if it's off the topic but do you think it would be possible to exclude only some file types from showing thumbnails?

As I mentioned .cbz previously I kind of liked that it didn't show CDisplayEx icon on the bottom right corner but sadly it kind of went into .psd and other formats as well. Do you think it would be possible to somehow disable only this type of icon? I tried to search in .reg for it but also unsuccesful.

Thanks a lot!

**Comment by mhetralla** [comment]
@Xanashi Thanks for the .reg file, that fixed the problem I had on the OP.

@MaitieS If you want to disable the icon on .psd thumbnails, go to "HKEY_CLASSES_ROOT\SystemFileAssociations\.psd" and create a string named "TypeOverlay" with nothing in the value. Restart explorer and .psd files won't have the program icon in the thumbnail.

**Comment by Xanashi** [comment]
@mhetralla Awesome! Happy to hear it! 👍 

@MaitieS Yep, the solution mhetralla provided is exactly how you do it for specific filetypes. 
I don't believe it possible to disable specific application icons though for all filetypes that icon affects.
Only specific filetypes, or filetype groups.
