### ISSUE TITLE
[QUESTION] What's the effect of "View Size"

### ISSUE THREAD

**Issue by masterofobzene** [Xanashi/Icaros#54]
What does that option do? I've set it to windows 10 icons, but the cache was showing really oversized thumbs (judging by their names like Icaros_1280 or Icaros_2560.icdb).

What is the effect of that option? can I set it to "large" to improve (reduce) cache size? I'm using the highest windows setting (i think its 256) for viewing thumbnails.

**Comment by Xanashi** [comment]
These options are no longer as relevant as they once were, since the release of Windows 8. 

In Windows 7 (and below), setting the View mode in Explorer to 'Small icons', 'Medium icons', 'Large icons' etc., actually had
an impact on what size thumbnails Explorer requested from the Shell Extensions.

For example, if you set the View mode to 'Large icons' in Windows 7, the thumbnail size requested would be 96x96px,
so it was recommended to set the View size in IcarosConfig to the same as in Explorer, so the Icaros Cache was already
loaded up with the correctly sized thumbnails, when Explorer called. 

However, in Windows 8 Microsoft changed this behavior. Now regardless of what View mode you used in Explorer, 
it would almost always request 1024x1024px thumbnails from the Shell Extensions. 
So in IcarosConfig it made most sense to always use the "Win 8 icons" size, to fill the Icaros Cache. 

In Windows 10+, they took this one step further, and started to always request 1280x1280px thumbnails from 
Shell Extensions, again regardless of the View mode in Explorer. 
So that's why IcarosConfig has a "Win 10 icons" option, that's selected by default in Win 10+. 

Unfortunately these changes from Microsoft, did have a massive impact on the size of the thumbnail caches, 
both the Icaros Cache, but also their own, but they probably have their reasons for choosing these specific sizes. 
It would be nice to have a bit more options though as users.

**Comment by masterofobzene** [comment]
Thanks, its clear now; its MS. They grab an HD thumb (source) and then resize it to smaller sizes if required instead of grabbing each thumb at each size. Saddly this impacts my cache size as I have an enormous library of pics and videos, still icaros is faster at generating/showing the thumbs than MS is so I will set it to "dynamic" and not use the "locations" to fill the cache, as it would go up to more than 256GB.

Thanks for your explanation.

**Comment by Xanashi** [comment]
You're welcome!

And unfortunately Windows also stores the HD thumbs, so the Window Cache also grows quite large quite fast on Win 10+.

**Comment by 4hench** [comment]
> These options are no longer as relevant as they once were, since the release of Windows 8.

cant you delete the view size column now? it just make people confused

**Comment by Xanashi** [comment]
Icaros still has quite a few Windows 7 and Vista users, so the option is still valid. 
I could hide it on Windows 8+, that would probably be a fine solution.
