### ISSUE TITLE
When Icarus properties active for video, can't edit the properties in Explorer?

### ISSUE THREAD

**Issue by IntelliMoo** [Xanashi/Icaros#65]
For example, in Icarus settings I turn on properties for MP4. Now I can no longer edit properties for MP4 files in Explorer, such as Title and the star rating. Said properties become editable again when turn off the setting in Icarus.

**Comment by Xanashi** [comment]
Yeah, Icaros does not currently support property editing, which is also why all MP4 formats are disabled by default in Icaros.

The reason why the option is there, is because Icaros provides additional info for MP4 formats that the native Property Handler
does not (such as Video and Audio tracks). Some users prefer the additional info, over the ability to edit in File Explorer. 
Adding editing is on the To-Do list but not a priority at the moment.
