### ISSUE TITLE
Thumbnails keeps refreshing

### ISSUE THREAD

**Issue by MaitieS** [Xanashi/Icaros#79]
Hi,

Since the last Friday I noticed that my thumbnails keeps refreshing. At first I wasn't fully sure of what is going on so I just shrugted it off as some minor issue but even after I manually cleaned up thumbnails and rebuilded my thumbnail library the issue still persist.

Description of the issue: When I open a folder it acts like it wants to rebuild thumbnails again even though I was in that folder a minute ago and it is already rebuilded.

Today I noticed that some thumbnails are not showing properly at all and that is when I realized that it could be due to Icarus program. So I turned off thumbnailing and it resolved the issue.

The thing is that... I didn't change anything in Icarus or on my PC perhaps commulitive update changed something but I updated it on the day of the release so almost 2 weeks ago, yet issue showed up only now.

If you need any further help please let me know. I wanted to gather more but it's kind of hard to replicate? From my persona experience it seems that Icarus & Windows Explorer started fighting each other which is why they are constantly refreshing.

update1: so far I tried to manually remove .jpg; .png from Icaros but it doesn't seem to help. I will try to update this after longer testing.
update1.5: it seems that by excluding other formats that there is a chance that it won't generate thumbnails at all for some reason and the only solution is to reactivate it again...

**Comment by Xanashi** [comment]
Hi MaitieS,

In my experience this is a bug related to File Explorer, and it is usually fixed by simply restarting Explorer (or Windows).
I've never seen it being directly related to Icaros. And realistically it shouldn't be, as Windows is entirely in charge of 
rendering and displaying the thumbnails in Explorer, as well as storing them in a cache, so they don't have to be regenerated
the next time you open the same folder again.

The only time Icaros is being called, is if a thumbnail is missing for a file, and File Explorer request this thumbnail from the
associated thumbnail provider, in this case Icaros.

**Comment by MaitieS** [comment]
Yeah I can confirm that it is File Explorer bug for sure because it is now working like nothing ever happened... and I'm really confused of why :D 
Thanks a lot! Next time I will report this bug directly to Microsoft, sorry for mistaking it with Icaros.
