### ISSUE TITLE
Any way to make Icaros "portable"?

### ISSUE THREAD

**Issue by GlasslessPizza** [Xanashi/Icaros#85]
By that I mean having the configuration being stored as a file near the executable instead of in the Windows Registry. This would allow very quick back-to-business after an OS reinstallation or when bringing it over to another machine.

**Comment by Xanashi** [comment]
Hi GlasslessPizza,

Since it was important that all shell extensions had permissions and easy access to the settings at all time, I ended up putting them in the Windows Registry for both the installed and portable builds. 

The easiest way to transfer these settings to a new system would be with the following IcarosConfig commands (CLI):

Save settings
1. IcarosConfig -deactivate
2. IcarosConfig -settings=exp -path="C:\Some\Path\Name"

Load settings
1. IcarosConfig -settings=imp -path="C:\Some\Path\Name\IcarosSettings.icss"
2. IcarosConfig -activate

And that should basically setup Icaros exactly the same on both machines (or on a reinstalled system)

**Comment by Xanashi** [comment]
Closing this issue for now. You can reopen it if you need more help. 😊
