### ISSUE TITLE
MP4 Property Handler

### ISSUE THREAD

**Issue by Coolie2** [Xanashi/Icaros#95]
I've found the property handling functionality of Icaros to be extremely useful, avoiding the need to use MediaInfo to view simple encoding properties. I was wondering if there's a reason why Icaros doesn't replace the property handler of mp4 files (MF MPEG-4 Property Handler by default), as such functionality would lessen the need to use MediaInfo even further.

**Comment by Xanashi** [comment]
Hi Coolie2,
So happy to hear you find Icaros useful. 
The reason why MP4 properties is not enabled by default in Icaros, is because Icaros does not offer editing of properties, while the  native Windows property handler does. 
So it's up to the individual user to determine which property handler they find most useful for their use case. 
The default which allows property editing or Icaros' property handler which provides more information about the file.
