### ISSUE TITLE
Changing language does not change language of properties

### ISSUE THREAD

**Issue by LesFerch** [Xanashi/Icaros#97]
Currently, property labels are always English:
```
Icaros.AudioTracks         Audio tracks
Icaros.BitDepth            Bit depth
Icaros.ContainsChapters    Contains chapters
Icaros.ContentCompression  Content compression
Icaros.SubtitleGroup       Subtitles
Icaros.SubtitleTracks      Subtitle tracks
Icaros.VideoTracks         Video tracks
```

With Icaros set to German, I would expect to see something like this:
```
Icaros.AudioTracks         Audiospuren
Icaros.BitDepth            Bittiefe
Icaros.ContainsChapters    Enthält Kapitel
Icaros.ContentCompression  Inhaltskomprimierung
Icaros.SubtitleGroup       Untertitel
Icaros.SubtitleTracks      Untertitelspuren
Icaros.VideoTracks         Videospuren
```
**Note**: I only speak English. The above is machine translated.

**Comment by Xanashi** [comment]
Hi,
You need to click the checkbox that appears under the combobox where you set the language in IcarosConfig to change the localization of the properties in Explorer.

**Comment by LesFerch** [comment]
Thank you!

I see why I missed that option. When the language is English, the option is not shown:
![image](https://github.com/Xanashi/Icaros/assets/79026235/b3de644d-3c7c-4e25-a8a6-7f2f682e5a2b)
When the language is changed, the option appears, but, because I only speak English, it didn't catch my attention:
![image](https://github.com/Xanashi/Icaros/assets/79026235/3d374f8b-da1a-4012-affa-7b2fc069e860)

Why would anyone change to a language they don't speak? Testing. Setting the configuration for someone else. Checking the integration with another program.

My suggestion is to always show the option and have it checked by default. It can be greyed out for English:
![image](https://github.com/Xanashi/Icaros/assets/79026235/83dc0742-229b-48c2-8411-3c8f507602e6)

**Comment by Xanashi** [comment]
Being able to set the language is fairly common practice in all software. 
Always give users the option, you can't anticipate their circumstances or preferences. 
As an example, my native language is not English, but I always prefer all my software to be set to English. 

The reason why I hide the checkbox when English is selected, is because the option simply isn't available in English,
and if I greyed out the checkbox, users would just start asking why that option is never available/clickable instead.
And then someone would tell me to "just remove it, if it's not an actual option".

**Comment by LesFerch** [comment]
Good point about the greyed out option, but I would still argue for the default to be checked. Not a big deal though.

**Comment by Xanashi** [comment]
And that is a good point.
I definitely think it makes sense to make enabled by default, if the OS language is set to the same language as the one selected in Icaros.
